import {Platform, StyleSheet} from "react-native";
import {
    CARD_RADIUS,
    SAFE_H_PADDING,
    SAFE_V_SPACING,
    STATUS_BAR_HEIGHT,
} from "./constants";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FBFA",
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 12,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#0f172a",
  },
  topNavContainer: {
    backgroundColor: "#F8FBFA",
    paddingTop:
      (Platform.OS === "ios" ? 44 : STATUS_BAR_HEIGHT) + SAFE_V_SPACING,
    borderBottomWidth: 1,
    borderBottomColor: "#E6ECE9",
  },
  topNav: {
    flexDirection: "row",
    paddingHorizontal: SAFE_H_PADDING,
    gap: 14,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabButtonActive: {
    borderBottomColor: "#2E7D64",
  },
  tabText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#94A3B8",
    letterSpacing: 0.2,
  },
  tabTextActive: {
    color: "#2E7D64",
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: SAFE_H_PADDING,
    paddingVertical: SAFE_V_SPACING,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SAFE_V_SPACING,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#0f172a",
  },
  viewAllText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#2E7D64",
  },
  questGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: SAFE_V_SPACING + 4,
  },
  questCard: {
    width: "48%",
    backgroundColor: "#ffffff",
    borderRadius: CARD_RADIUS,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E6ECE9",
    shadowColor: "#0F172A",
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 4},
    elevation: 2,
  },
  questTag: {
    alignSelf: "flex-start",
    backgroundColor: "#2E7D64",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    marginBottom: 8,
  },
  questTagText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 0.3,
  },
  questTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 8,
  },
  questMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
    marginBottom: 6,
  },
  questMetaPill: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: "#E6ECE9",
    justifyContent: "center",
  },
  questMetaText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#0f172a",
  },
  questTime: {
    fontSize: 10,
    fontWeight: "600",
    color: "#64748b",
    marginBottom: 10,
  },
  questButton: {
    backgroundColor: "#2E7D64",
    borderRadius: 12,
    paddingVertical: 8,
    alignItems: "center",
  },
  questButtonSubmitted: {
    backgroundColor: "#1F6A54",
  },
  questButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#ffffff",
  },
  bingoCard: {
    backgroundColor: "#ffffff",
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: "#E6ECE9",
    padding: 12,
    marginBottom: SAFE_V_SPACING + 4,
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 4},
    elevation: 2,
  },
  bingoHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  bingoTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
  },
  bingoChip: {
    backgroundColor: "#e2f8f1",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  bingoChipText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#0f766e",
  },
  bingoRow: {
    marginBottom: 10,
  },
  bingoRowTitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#0f172a",
    marginBottom: 6,
  },
  bingoProgressTrack: {
    height: 6,
    backgroundColor: "#e2e8f0",
    borderRadius: 999,
    overflow: "hidden",
  },
  bingoProgressFill: {
    height: "100%",
    backgroundColor: "#2E7D64",
  },
  bingoProgressText: {
    fontSize: 10,
    fontWeight: "600",
    color: "#64748b",
    marginTop: 4,
  },
  bingoButton: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#2E7D64",
    borderRadius: 12,
    paddingVertical: 8,
    alignItems: "center",
  },
  bingoButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#2E7D64",
  },
  leaderboardCard: {
    backgroundColor: "#ffffff",
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: "#E6ECE9",
    paddingVertical: 6,
    marginBottom: 8,
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 4},
    elevation: 2,
  },
  leaderboardRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  leaderboardRank: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  leaderboardRankText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
  },
  leaderboardAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    marginRight: 10,
  },
  leaderboardInfo: {
    flex: 1,
  },
  leaderboardName: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0f172a",
  },
  leaderboardBadge: {
    fontSize: 10,
    fontWeight: "600",
    color: "#64748b",
    marginTop: 2,
  },
  leaderboardPoints: {
    fontSize: 12,
    fontWeight: "700",
    color: "#2E7D64",
  },
  featuredCard: {
    borderRadius: CARD_RADIUS + 2,
    overflow: "hidden",
    backgroundColor: "#f1f5f9",
    marginBottom: SAFE_V_SPACING,
    shadowColor: "#0F172A",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 6},
    elevation: 3,
  },
  featuredImage: {
    width: "100%",
    height: 180,
  },
  featuredOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 14,
    backgroundColor: "rgba(15, 23, 42, 0.55)",
  },
  tagPill: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(16, 185, 129, 0.9)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    marginBottom: 8,
  },
  tagText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 0.3,
  },
  featuredTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
  },
  newsList: {
    gap: 12,
    marginBottom: SAFE_V_SPACING,
  },
  newsItem: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
    backgroundColor: "#ffffff",
    padding: 10,
    borderRadius: CARD_RADIUS,
    borderWidth: 1,
    borderColor: "#E6ECE9",
  },
  newsThumb: {
    width: 70,
    height: 70,
    borderRadius: 12,
  },
  newsTextBlock: {
    flex: 1,
  },
  newsCategory: {
    fontSize: 10,
    fontWeight: "700",
    color: "#2E7D64",
  },
  newsTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
    marginVertical: 4,
  },
  newsMeta: {
    fontSize: 11,
    fontWeight: "500",
    color: "#94a3b8",
  },
  roadAlertsCard: {
    backgroundColor: "#fff7ed",
    borderRadius: CARD_RADIUS,
    padding: 12,
    marginBottom: SAFE_V_SPACING,
    borderWidth: 1,
    borderColor: "#F5E5D5",
  },
  roadAlertsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  roadAlertsTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#c2410c",
  },
  alertItem: {
    flexDirection: "row",
    gap: 10,
    backgroundColor: "#ffffff",
    borderRadius: CARD_RADIUS - 2,
    padding: 10,
    marginBottom: 10,
    alignItems: "flex-start",
    borderWidth: 1,
    borderColor: "#F2E8DA",
  },
  alertBar: {
    width: 4,
    height: "100%",
    borderRadius: 4,
  },
  alertTextBlock: {
    flex: 1,
  },
  alertTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 4,
  },
  alertDetail: {
    fontSize: 11,
    fontWeight: "500",
    color: "#6b7280",
  },
  spotlightRow: {
    marginTop: 15,
    gap: 12,
    paddingBottom: SAFE_V_SPACING,
  },
  spotlightCard: {
    width: 170,
    borderRadius: CARD_RADIUS,
    overflow: "hidden",
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#E6ECE9",
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 4},
    elevation: 2,
  },
  spotlightImage: {
    width: "100%",
    height: 120,
  },
  spotlightContent: {
    padding: 12,
  },
  spotlightName: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0f172a",
  },
  spotlightSubtitle: {
    fontSize: 11,
    fontWeight: "500",
    color: "#64748b",
    marginVertical: 6,
  },
  spotlightButton: {
    borderWidth: 1,
    borderColor: "#2E7D64",
    paddingVertical: 6,
    borderRadius: 16,
    alignItems: "center",
  },
  spotlightButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#2E7D64",
  },
  placeholderText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#999999",
    textAlign: "center",
    marginTop: 40,
  },
  imagePlaceholder: {
    backgroundColor: "#E5E7EB",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: CARD_RADIUS + 2,
    padding: 16,
  },
  modalImage: {
    width: "100%",
    height: 160,
    borderRadius: 12,
    marginBottom: 12,
  },
  modalName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  modalSubtitle: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748b",
    marginTop: 4,
  },
  modalMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 10,
  },
  modalMetaText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#0f172a",
  },
  modalJourney: {
    fontSize: 12,
    fontWeight: "500",
    color: "#475569",
    marginTop: 10,
    lineHeight: 18,
  },
  modalCloseButton: {
    marginTop: 14,
    backgroundColor: "#2E7D64",
    paddingVertical: 10,
    borderRadius: 16,
    alignItems: "center",
  },
  modalCloseText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#ffffff",
  },
  gameModalCard: {
    width: "100%",
    backgroundColor: "#ffffff",
    borderRadius: CARD_RADIUS + 2,
    padding: 16,
  },
  gameModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  gameModalTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0f172a",
  },
  gameModalClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#f1f5f9",
    alignItems: "center",
    justifyContent: "center",
  },
  gameModalSubtext: {
    fontSize: 12,
    fontWeight: "600",
    color: "#64748b",
    marginBottom: 12,
  },
  cameraPreview: {
    height: 180,
    borderRadius: CARD_RADIUS,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: SAFE_V_SPACING,
    gap: 6,
    overflow: "hidden",
  },
  cameraPreviewImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  cameraPreviewCamera: {
    width: "100%",
    height: "100%",
  },
  cameraPreviewText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "600",
  },
  cameraActions: {
    flexDirection: "row",
    gap: 10,
  },
  cameraActionGhost: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#2E7D64",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  cameraActionGhostText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#2E7D64",
  },
  cameraActionPrimary: {
    flex: 1,
    backgroundColor: "#2E7D64",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  cameraActionPrimaryText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#ffffff",
  },
});
