import {Platform, StatusBar, StyleSheet} from "react-native";
const STATUS_BAR_HEIGHT =
  Platform.OS === "android" ? (StatusBar.currentHeight ?? 0) : 0;
const SAFE_TOP_PADDING = Math.max(0, STATUS_BAR_HEIGHT);

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
    paddingTop: SAFE_TOP_PADDING,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  headerIconButton: {
    padding: 8,
    borderRadius: 8,
  },
  headerIconSpacer: {
    width: 40,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1F2937",
    textAlign: "center",
    flex: 1,
    letterSpacing: 0.2,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
  },
  sectionLabel: {
    marginTop: 12,
    fontSize: 11,
    letterSpacing: 1.2,
    color: "#2e7d64",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  sectionLabelSpacing: {
    marginTop: 24,
  },
  sectionTitle: {
    marginTop: 8,
    fontSize: 20,
    fontWeight: "700",
    color: "#1F2937",
    letterSpacing: 0.2,
  },
  mapCard: {
    marginTop: 16,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    padding: 16,
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  mapPreview: {
    height: 200,
    borderRadius: 16,
    backgroundColor: "#F3F4F6",
    borderWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    position: "relative",
  },
  mapPreviewText: {
    marginTop: 6,
    fontSize: 12,
    color: "#9CA3AF",
    fontWeight: "600",
  },
  mapLocationPill: {
    position: "absolute",
    top: 12,
    right: 12,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#ECFDF5",
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "#A7F3D0",
    maxWidth: 160,
  },
  mapLocationText: {
    marginLeft: 4,
    fontSize: 11,
    fontWeight: "600",
    color: "#065F46",
  },
  mapBadge: {
    position: "absolute",
    bottom: 12,
    left: 12,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: "#2e7d64",
    borderRadius: 999,
    borderWidth: 0,
    shadowColor: "#2e7d64",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  mapBadgeText: {
    marginLeft: 6,
    fontSize: 12,
    fontWeight: "600",
    color: "#ffffff",
  },
  card: {
    marginTop: 16,
    borderRadius: 18,
    backgroundColor: "#ffffff",
    padding: 16,
    borderWidth: 0,
    shadowColor: "#000",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  cardEyebrow: {
    fontSize: 12,
    color: "#2e7d64",
    fontWeight: "800",
  },
  cardTitle: {
    marginTop: 6,
    fontSize: 18,
    fontWeight: "700",
    color: "#1F2937",
    letterSpacing: 0.2,
  },
  cardDescription: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 20,
    color: "#6B7280",
  },
  segmented: {
    marginTop: 14,
    flexDirection: "row",
    padding: 4,
    borderRadius: 14,
    backgroundColor: "#F3F4F6",
    borderWidth: 0,
  },
  segment: {
    flex: 1,
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  segmentSelected: {
    backgroundColor: "#2e7d64",
    shadowColor: "#2e7d64",
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 2,
  },
  segmentText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#9CA3AF",
  },
  segmentTextSelected: {
    color: "#ffffff",
  },
  topBar: {
    height: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    marginTop: 4,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#2e7d64",
  },
  backButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  topBarSpacer: {
    width: 44,
    height: 44,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
  },
  rowLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    paddingRight: 10,
  },
  rowIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  rowTextWrap: {
    flex: 1,
  },
  rowTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2937",
  },
  rowSubtitle: {
    marginTop: 3,
    fontSize: 13,
    color: "#6B7280",
  },
  divider: {
    height: 1,
    backgroundColor: "#E5E7EB",
  },
  contactRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  contactLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    paddingRight: 10,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#f0fdf9",
    borderWidth: 2,
    borderColor: "#2e7d64",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  avatarText: {
    color: "#2e7d64",
    fontWeight: "700",
    fontSize: 16,
  },
  contactTextWrap: {
    flex: 1,
  },
  contactName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1F2937",
  },
  contactSubtitle: {
    marginTop: 3,
    fontSize: 12,
    color: "#2e7d64",
    fontWeight: "600",
  },
  contactAction: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  addTrustedButton: {
    marginTop: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 13,
    borderRadius: 14,
    backgroundColor: "#f0fdf9",
    borderWidth: 1.5,
    borderColor: "#2e7d64",
    borderStyle: "dashed",
  },
  addTrustedButtonIcon: {
    marginRight: 8,
  },
  addTrustedButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#2e7d64",
  },
  tipCard: {
    marginTop: 18,
    flexDirection: "row",
    alignItems: "flex-start",
    borderRadius: 16,
    backgroundColor: "#f0fdf9",
    borderWidth: 1,
    borderColor: "#9ed6c3",
    padding: 14,
    shadowColor: "#2e7d64",
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  tipIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 12,
    backgroundColor: "#2e7d64",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  tipText: {
    flex: 1,
    color: "#065F46",
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "500",
  },
  mapContent: {
    marginTop: 16,
  },
});
