import {Dimensions, Platform, StatusBar, StyleSheet} from "react-native";

const {width: WINDOW_WIDTH, height: WINDOW_HEIGHT} = Dimensions.get("window");
const TOP_BAR_PADDING =
  Platform.OS === "ios" ? 44 : (StatusBar.currentHeight ?? 0) + 12;
const H_PADDING = Math.max(16, Math.round(WINDOW_WIDTH * 0.045));
const V_SPACING = Math.max(10, Math.round(WINDOW_HEIGHT * 0.012));
const SECTION_SPACING = Math.max(12, Math.round(WINDOW_HEIGHT * 0.016));

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F7FAF9",
    paddingHorizontal: H_PADDING,
    paddingTop: TOP_BAR_PADDING,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: SECTION_SPACING,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#0F172A",
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E6ECE9",
    alignItems: "center",
    justifyContent: "center",
  },
  iconBadge: {
    position: "absolute",
    top: 8,
    right: 9,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#2E7D64",
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E6ECE9",
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 4},
    elevation: 2,
    marginBottom: SECTION_SPACING,
  },
  searchInput: {
    flex: 1,
    color: "#0F172A",
    fontSize: 12,
    fontWeight: "500",
    padding: 0,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: V_SPACING,
  },
  sectionHeaderText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#94A3B8",
    letterSpacing: 0.6,
    marginBottom: V_SPACING,
  },
  createButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#ECFDF5",
    borderWidth: 1,
    borderColor: "#9ED6C3",
    paddingHorizontal: 10,
    paddingVertical: 2,
    marginRight: 5,
    borderRadius: 999,
  },
  createButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#2E7D64",
  },
  createPlus: {
    fontSize: 16,
    fontWeight: "700",
    color: "#2E7D64",
  },
  createModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    justifyContent: "center",
    paddingHorizontal: H_PADDING,
  },
  createModalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 18,
    width: "100%",
    shadowColor: "#0F172A",
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: {width: 0, height: 10},
    elevation: 4,
  },
  createModalScroll: {
    flexGrow: 0,
  },
  createModalContent: {
    paddingBottom: 4,
  },
  createModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  createModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F172A",
  },
  createModalClose: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  createLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#64748B",
    marginBottom: 6,
  },
  createInput: {
    borderWidth: 1,
    borderColor: "#E2E8F0",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    color: "#0F172A",
    marginBottom: 14,
  },
  imageUploadSection: {
    marginBottom: 16,
  },
  imageUploadBox: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    backgroundColor: "#F8FAFC",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  imagePreview: {
    width: "100%",
    height: "100%",
  },
  imageUploadText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#94A3B8",
    marginTop: 8,
  },
  createModalActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  createCancelButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
  },
  createCancelText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#64748B",
  },
  createSubmitButton: {
    flex: 1,
    backgroundColor: "#2E7D64",
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
  },
  createSubmitText: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  imagePlaceholder: {
    backgroundColor: "#E5E7EB",
  },
  suggestedRow: {
    flexDirection: "row",
    paddingRight: H_PADDING,
    gap: 12,
    marginBottom: SECTION_SPACING,
  },
  communityCard: {
    width: 180,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E6ECE9",
    shadowColor: "#0F172A",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 6},
    elevation: 2,
  },
  communityImage: {
    height: 90,
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 10,
    backgroundColor: "#E2E8F0",
  },
  communityImageFill: {
    width: "100%",
    height: "100%",
  },
  communityName: {
    fontSize: 12,
    fontWeight: "700",
    color: "#0F172A",
  },
  communityCreator: {
    fontSize: 10,
    color: "#94A3B8",
    marginTop: 2,
  },
  communityMembers: {
    fontSize: 10,
    color: "#94A3B8",
    marginBottom: 10,
  },
  joinButton: {
    backgroundColor: "#2E7D64",
    paddingVertical: 8,
    borderRadius: 16,
    alignItems: "center",
  },
  joinButtonText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  joinedButton: {
    backgroundColor: "#E2E8F0",
    paddingVertical: 8,
    borderRadius: 16,
    alignItems: "center",
  },
  joinedButtonText: {
    color: "#475569",
    fontSize: 12,
    fontWeight: "600",
  },
  listCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginBottom: SECTION_SPACING,
    borderWidth: 1,
    borderColor: "#E6ECE9",
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 4},
    elevation: 1,
  },
  listItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
  },
  listAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    overflow: "hidden",
    marginRight: 10,
    position: "relative",
  },
  listAvatarImage: {
    width: "100%",
    height: "100%",
  },
  listTextWrap: {
    flex: 1,
  },
  listTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#0F172A",
  },
  listSubtitle: {
    fontSize: 11,
    color: "#94A3B8",
  },
  listMeta: {
    fontSize: 10,
    color: "#94A3B8",
  },
  onlineDot: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#2E7D64",
    borderWidth: 1,
    borderColor: "#ffffff",
  },
  legacyModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.35)",
    justifyContent: "flex-end",
  },
  legacyModalCard: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: "hidden",
    height: "95%",
  },
  legacyModalTopBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: H_PADDING,
    paddingTop: TOP_BAR_PADDING,
    paddingBottom: 8,
  },
  tabsTopDivider: {
    height: 1,
    backgroundColor: "#f0f0f0",
  },
  legacyModalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1a1a1a",
    marginLeft: 6,
  },
  legacyBackButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1F5F9",
  },
  legacyContainer: {
    backgroundColor: "#ffffff",
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: "#F7FAF9",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: H_PADDING,
    paddingTop: TOP_BAR_PADDING,
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#E6ECE9",
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1a1a1a",
  },
  markAllText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2E7D64",
  },
  markAllButton: {
    marginLeft: "auto",
  },
  tabsContainer: {
    flexDirection: "row",
    paddingHorizontal: H_PADDING,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E6ECE9",
    gap: 12,
  },
  tab: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#E6ECE9",
  },
  tabActive: {
    backgroundColor: "#2E7D64",
    borderColor: "#2E7D64",
  },
  tabText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#666666",
  },
  tabTextActive: {
    color: "#ffffff",
  },
  notificationsList: {
    flex: 1,
    paddingHorizontal: H_PADDING,
    paddingTop: SECTION_SPACING,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#888888",
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  notificationCard: {
    flexDirection: "row",
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 12,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E6ECE9",
    shadowColor: "#0F172A",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 4},
    elevation: 2,
    alignItems: "center",
    position: "relative",
  },
  notificationCardRead: {
    backgroundColor: "#F8FBFA",
    shadowOpacity: 0.02,
    elevation: 1,
  },
  avatarWrapper: {
    marginRight: 14,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  avatarBadge: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#ECFDF5",
    borderWidth: 1,
    borderColor: "#9ED6C3",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#2E7D64",
    position: "absolute",
    top: 12,
    right: 12,
    borderWidth: 2,
    borderColor: "#ffffff",
  },
  notificationContent: {
    flex: 1,
    justifyContent: "center",
  },
  notificationTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 4,
  },
  notificationMessage: {
    fontSize: 13,
    fontWeight: "400",
    color: "#555555",
    marginBottom: 6,
    lineHeight: 18,
  },
  notificationTime: {
    fontSize: 12,
    fontWeight: "500",
    color: "#999999",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 24,
  },
  emptyText: {
    fontSize: 13,
    color: "#94A3B8",
  },
  errorText: {
    marginTop: 8,
    fontSize: 12,
    color: "#EF4444",
  },
  unreadIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#2E7D64",
    marginLeft: 12,
    alignSelf: "center",
  },
  chatModal: {
    flex: 1,
    backgroundColor: "#F7FAF9",
  },
  chatHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: H_PADDING,
    paddingTop: TOP_BAR_PADDING,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E6ECE9",
    backgroundColor: "#F7FAF9",
  },
  chatHeaderAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  chatBackButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E6ECE9",
    alignItems: "center",
    justifyContent: "center",
  },
  chatHeaderText: {
    flex: 1,
  },
  chatTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#0F172A",
  },
  chatSubtitle: {
    fontSize: 12,
    color: "#94A3B8",
    marginTop: 2,
  },
  chatMessages: {
    flex: 1,
  },
  chatMessagesContent: {
    paddingHorizontal: H_PADDING,
    paddingTop: SECTION_SPACING,
    paddingBottom: Math.max(24, SECTION_SPACING + 8),
    gap: 10,
  },
  chatRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    width: "100%",
  },
  chatRowMe: {
    justifyContent: "flex-end",
  },
  chatRowSystem: {
    justifyContent: "center",
  },
  chatAvatarWrap: {
    width: 28,
    alignItems: "center",
  },
  chatAvatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
  },
  chatAvatarFallback: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  chatBubble: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E6ECE9",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    maxWidth: "80%",
  },
  chatBubbleMe: {
    alignSelf: "flex-end",
    backgroundColor: "#2E7D64",
    borderColor: "#2E7D64",
  },
  chatBubbleSystem: {
    alignSelf: "center",
    backgroundColor: "#F1F5F9",
    borderColor: "#E2E8F0",
  },
  chatBubbleText: {
    fontSize: 13,
    color: "#0F172A",
  },
  chatSenderName: {
    fontSize: 11,
    color: "#64748B",
    fontWeight: "600",
    marginBottom: 2,
  },
  chatBubbleTextMe: {
    color: "#ffffff",
  },
  chatBubbleTextSystem: {
    color: "#475569",
  },
  chatTimestamp: {
    fontSize: 10,
    color: "#94A3B8",
    marginTop: 4,
  },
  chatComposer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: H_PADDING,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 16 : 12,
    borderTopWidth: 1,
    borderTopColor: "#E6ECE9",
    backgroundColor: "#FFFFFF",
    gap: 10,
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E6ECE9",
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    color: "#0F172A",
  },
  chatSendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#2E7D64",
    alignItems: "center",
    justifyContent: "center",
  },
});
